### PR TITLE
Expose the set index() function as indexOf()

### PR DESCRIPTION
**Pull request by Twipped**
It'd be beneficial to be able to identify the location of an item in the set.

### CODE REVIEW

**Comment by dominictarr** [comment]
yup, this is reasonable.

**Comment by dominictarr** [comment]
merged into 1.1.0

**Comment by Twipped** [comment]
@dominictarr I don't think this ever actually got merged. The commit history just shows you incrementing package.json

**Comment by dominictarr** [comment]
you are correct. sorry about that.
merging again... 1.2.0 this time.

**Comment by Twipped** [comment]
Cool, thanks

**Pull request merged**
